# This is a basic workflow to help you get started with Actions

name: Build and Test TicTacToe

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    SOURCE_DIR:   ${{ github.workspace }}
    QT_VERSION:   6.6.0
    ARTIFACT:     TicTacToe_V8

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt3d
          setup-python: false

      - name: Configure build
        run: |
          mkdir build
          cd build
          qmake ../TicTacToe_V8.pro

      - name: Build project
        run: |
          cd build
          make
